project_id = "lslysfupujprybfhkrdu"

[functions.daily-snapshot]
verify_jwt = false

[functions.og88-price-proxy]
verify_jwt = false

[functions.chat-wchain]
verify_jwt = false

[functions.refresh-leaderboard-cache]
verify_jwt = false