project_id = "lslysfupujprybfhkrdu"

[functions.daily-snapshot]
verify_jwt = false

[functions.og88-price-proxy]
verify_jwt = false

[functions.chat-wchain]
verify_jwt = true

[functions.refresh-leaderboard-cache]
verify_jwt = false

[functions.refresh-leaderboard-cache.schedule]
cron = "0 */6 * * *"

[functions.daily-snapshot.schedule]
cron = "0 19 * * *"

[functions.telegram-bot]
verify_jwt = false